name: Update Fuel Prices
on:
  schedule:
    - cron: '*/5 * * * *' # S'exécute toutes les 5 minutes
  workflow_dispatch: # Permet de le lancer à la main

jobs:
  build:
    runs-on: ubuntu-latest
    # Ajout explicite des permissions pour éviter les blocages
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python update_prices.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add prix.json
          git commit -m "Mise à jour automatique des prix" || exit 0
          git push
